#!/usr/bin/env python3
"""Check every Condition CR number in the report's tables against the data file.

WHY THIS EXISTS. The report carried TWO Condition CR tables with different numbers and
nothing noticed: section 1's headline table had the current values while section 6's
detailed table still held the published ones, so one geometry read 191.006 counts on one
page and 188.031 on another. Both tables looked internally fine. Only a cross-check sees it.
It also caught section 1's H row left at the pre-measurement value after the measured one
landed.

IT COMPARES WITHIN ONE OPERATING POINT AND REFUSES TO CROSS THEM (D076). The first version
matched rows by shape and promptly "found" twelve disagreements that were the EARLY and
LATE CRUISE tables, whose numbers differ because the operating point differs: M 0.78 at
C_L 0.529297087450 and 0.544114800210 against Condition CR's M 0.10 at 0.428277635108.
Comparing those against Condition CR data is precisely the mistake the report warns readers
not to make. So tables are identified by their OWN \\label, and only the declared Condition
CR labels are compared; every other table is EXCLUDED BY NAME with its label printed.

HOW IT PARSES. Rows are split on `&` and read by position. Three ad-hoc regexes written
during one session each produced a FALSE disagreement (one missed the escaped underscore
in `SWB\\_trim`, one used `[a-z ]+` against a label containing "TE"), and a checker that
cries wolf gets ignored.

EVERY TABLE AND EVERY ROW LANDS IN A NAMED BUCKET AND THE BUCKETS ARE ASSERTED TO SUM
(GEO-087). An unlabelled table is a FAILURE, not a skip: it is the case where this check
would silently stop covering something.
"""
import json
import re
import sys
from pathlib import Path

# THE DATA ROOT IS FOUND, NOT ASSUMED. This was parent.parent, which is the report
# root only when data/, fig/ and scripts/ are siblings. The delivery repo lifts data/
# to its own root, so the assumption held in one layout and failed silently in the
# other. data_root() walks up for the directory whose data/ carries rans_forces.json
# and RAISES if there is none, rather than returning a plausible wrong tree.
# In the working repo and in an assembled build directory it returns exactly what
# parent.parent returned, so this changes no behaviour there.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from report_paths import data_root  # noqa: E402
HERE = data_root()
LETTERS = ["B", "C", "M", "F", "W", "H"]

# The Condition CR tables, by their own \label, and which 0-based field holds C_D.
# A label NOT listed here is excluded with its name printed, never silently skipped.
CR_TABLES = {
    "tab:perf:cr": 3,
}
# tab:project-headline WAS the second entry here. The 22 September restructure dropped it:
# every column it carried is in tab:perf:cr, tab:perf:ec or tab:lo:selection, and it had no
# generator of its own, so it was the one place a hand-transcribed Condition CR number could
# still land. One Condition CR C_D table is the point; this check now guards that it stays one.

# Declared exclusions: tables that legitimately carry no Condition CR C_D column. Naming
# them, rather than letting them fall through, is what stops this check quietly narrowing.
EXCLUDED = {
    "tab:project-scope": "case inventory, counts and the word 'solved', no coefficients",
    "tab:lo:selection": "Condition CR INCREMENTS and ranks, not C_D; generated by make_rank_table.py",
    "tab:qv:vlm": "VSPAERO's own Condition CR columns, no RANS C_D",
    "tab:qv:lift": "trim angle RANS against VLM at Condition CR, no C_D",
    "tab:hinge": "hinge moment, three conditions, letter-initial rows but no C_D",
    "tab:rbm": "root bending at Condition CR, letter-initial rows but no C_D",
    "tab:cond:points": "operating points, no per-geometry rows",
}

# EVERY section file of the restructured report, so that every table in the document is
# enumerated into a bucket. A file left off this list is a table nobody is checking.
FILES = ["sections/t1_objectives.tex", "sections/t2_conditions_geometries.tex",
         "sections/t3_setup_pipeline.tex", "sections/t4_quantities.tex", "sections/t5_results.tex",
         "sections/t6_vlm_verdict.tex", "sections/t7_conclusions.tex", "sections/tA_sections.tex",
         "sections/tB_delta_maps.tex"]


def tables_in(text):
    """Yield (label, [(lineno, raw line)]) for each table environment."""
    lines = text.split("\n")
    out, cur, start = [], None, 0
    for n, line in enumerate(lines, 1):
        if "\\begin{table}" in line:
            cur, start = [], n
        elif "\\end{table}" in line and cur is not None:
            body = "\n".join(l for _, l in cur)
            m = re.search(r"\\label\{([^}]+)\}", body)
            out.append((m.group(1) if m else None, start, cur))
            cur = None
        elif cur is not None:
            cur.append((n, line))
    return out


def fields(line):
    body = line.strip()
    if not body.endswith("\\\\"):
        return None
    return [c.strip() for c in body[:-2].split("&")]


def number(cell):
    t = cell.replace("$", "").replace("\\,", "").strip()
    try:
        return float(t)
    except ValueError:
        return None


def main():
    cr = json.loads((HERE / "data/rans_forces.json").read_text())
    cr = cr["trims"]["condition_CR"]["geometries"]

    n_tables = n_checked = n_excluded = 0
    unlabelled, bad, unreadable, compared = [], [], [], 0

    for rel in FILES:
        path = HERE / rel
        if not path.exists():
            print("ABSENT %s" % rel)
            continue
        for label, start, rows in tables_in(path.read_text()):
            n_tables += 1
            if label is None:
                unlabelled.append((rel, start))
                continue
            if label not in CR_TABLES:
                n_excluded += 1
                why = EXCLUDED.get(label, "not a Condition CR table")
                print("EXCLUDED %-26s %s (%s)" % (label, rel, why))
                continue
            n_checked += 1
            col = CR_TABLES[label]
            print("\n=== %s  [%s] ===" % (rel, label))
            for n, line in rows:
                f = fields(line)
                if not f or not f[0] or f[0] not in LETTERS:
                    continue
                L = f[0]
                got = number(f[col]) if col < len(f) else None
                if got is None:
                    unreadable.append((rel, n, L, label))
                    continue
                want = cr[L]["Cd_counts"]
                compared += 1
                ok = abs(got - want) < 5e-4
                if not ok:
                    bad.append((rel, n, L, got, want))
                print("  line %-4d %s  table %9.3f   data %9.3f   %s"
                      % (n, L, got, want, "OK" if ok else "DISAGREES"))

    print()
    for rel, n in unlabelled:
        print("UNLABELLED TABLE %s starting line %d: cannot tell which operating point it "
              "is, so it cannot be checked or excluded" % (rel, n))
    for rel, n, L, label in unreadable:
        print("UNREADABLE %s:%d [%s] %s: C_D cell is not a number" % (rel, n, label, L))
    for rel, n, L, got, want in bad:
        print("DISAGREES %s:%d  %s table %.3f vs data %.3f" % (rel, n, L, got, want))

    assert n_checked + n_excluded + len(unlabelled) == n_tables, "bucket sum does not close"
    print("tables: %d = %d Condition CR + %d excluded + %d unlabelled"
          % (n_tables, n_checked, n_excluded, len(unlabelled)))
    print("rows compared: %d; disagreeing: %d; unreadable: %d"
          % (compared, len(bad), len(unreadable)))
    return 1 if (bad or unreadable or unlabelled) else 0


if __name__ == "__main__":
    sys.exit(main())
