#!/usr/bin/env python3
"""Emit every cruise table of the report as LaTeX fragments, read from the data files (ARG-196).

WHY FRAGMENTS, NOT PASTED ROWS. The early- and late-cruise tables were typed into the
section files by hand, and every one of their numbers changed when the cruise trims moved to
the welded meshes. A pasted row is a second copy that nothing keeps in step; a fragment that
the section \\input's is regenerated with the data. make_cr_table.py prints rows for pasting
and that stays as it is; the cruise tables are new enough to do it properly.

WRITES (sections/gen/, each file headed with its generator and sources):
  tab_perf_ec_rows.tex, tab_perf_lc_rows.tex   trimmed performance rows, ranked by dCD
  tab_hinge_rows.tex                            hinge moment, all 18 condition x geometry cells
  tab_rbm_cruise.tex                            cruise root bending and utilisation
  tab_trim_legs.tex                             every welded trim leg: alpha, C_L, C_D, nudge
  tab_generation_null.tex                       published against welded, per geometry
  cruise_values.json                            every number the prose quotes, with its source
SOURCES: data/rans_forces.json (trims, cases, superseded entries), fig/hinge_moment_values.csv,
results/derived/<prefix><L>_welded.json through fig/derived_source.py, data/welded_mesh_facts.tsv.
"""
import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "fig"))
from report_paths import data_root  # noqa: E402
import derived_source  # noqa: E402

ROOT = data_root()
DATA = ROOT / "data/rans_forces.json"
HINGE = HERE.parent / "fig/hinge_moment_values.csv"
MESH = ROOT / "data/welded_mesh_facts.tsv"
OUT = HERE.parent / "sections/gen"
GEOMS = "BCFHMW"
NAMES = {"B": "baseline EET AR12", "C": r"\texttt{cte\_i002\_c04}", "F": r"\texttt{cfft\_b02\_c01}",
         "H": r"\texttt{chc\_g02\_c06}", "M": r"\texttt{mcv2\_i002\_c01}", "W": r"\texttt{cffw\_b01\_c01}"}
COND = {"early_cruise": dict(prefix="CMP", label="Early cruise"),
        "late_cruise": dict(prefix="LC", label="Late cruise")}
HEAD = "%% GENERATED by scripts/make_cruise_tables.py from %s. Do not edit; rerun the script.\n"


def tt(s):
    return r"\texttt{%s}" % s.replace("_", r"\_")


def write(name, body, sources):
    OUT.mkdir(exist_ok=True)
    p = OUT / name
    p.write_text(HEAD % ", ".join(sources) + body)
    print("  wrote %s (%d lines)" % (p.relative_to(HERE.parent), body.count("\n")))


def perf(d, vals):
    for cond, c in COND.items():
        t = d["trims"][cond]
        g = t["geometries"]
        ranked = sorted((L for L in GEOMS if L != "B"), key=lambda L: g[L]["delta_Cd_counts_vs_baseline"])
        rank = {L: i + 1 for i, L in enumerate(ranked)}
        rows = []
        for L in ["B"] + ranked:
            e = g[L]
            rows.append("%s & %s & %.4f & %.3f & $%+.3f$ & $%+.3f$ & %.3f & %s \\\\\n"
                        % (L, tt(e["trim_case"]), e["alpha_deg"], e["Cd_counts"],
                           e["delta_Cd_counts_vs_baseline"], e["Cl_minus_target_counts"],
                           e["L_over_D"], "--" if L == "B" else rank[L]))
        tag = "ec" if cond == "early_cruise" else "lc"
        write("tab_perf_%s_rows.tex" % tag, "".join(rows), ["data/rans_forces.json trims." + cond])
        vals[cond] = dict(
            baseline_Cd_counts=t["baseline_Cd_counts"], target_CL=t["target_CL"],
            order=ranked,
            delta={L: g[L]["delta_Cd_counts_vs_baseline"] for L in GEOMS},
            Cd={L: g[L]["Cd_counts"] for L in GEOMS}, alpha={L: g[L]["alpha_deg"] for L in GEOMS},
            LD={L: g[L]["L_over_D"] for L in GEOMS},
            Cl_minus_target={L: g[L]["Cl_minus_target_counts"] for L in GEOMS},
            worst_abs_Cl_residual=max(abs(g[L]["Cl_minus_target_counts"]) for L in GEOMS),
            bias={L: g[L]["Cd_bias_from_trim_residual_counts"] for L in GEOMS},
            incidence_below_B={L: g["B"]["alpha_deg"] - g[L]["alpha_deg"] for L in GEOMS if L != "B"})


def generation_null(d, vals):
    """Published against welded, per geometry. B, C and M were built from sound surfaces and are
    the KNOWN-ANSWER null: a correct re-run must reproduce them. F, H and W carried the seam."""
    rows, out = [], {}
    for cond, c in COND.items():
        rows.append(r"\multicolumn{6}{l}{\emph{%s}} \\" % c["label"] + "\n")
        for L in GEOMS:
            e = d["cases"]["%s%s_trim" % (c["prefix"], L)]
            old = e["superseded_entry"]
            dcd = e["Cd_counts"] - old["Cd_counts"]
            dcl = (e["Cl"] - old["Cl"]) * 1e4
            role = "seam" if L in "FHW" else "sound"
            rows.append("%s & %s & %.3f & %.3f & $%+.3f$ & $%+.3f$ \\\\\n"
                        % (L, role, old["Cd_counts"], e["Cd_counts"], dcd, dcl))
            out["%s/%s" % (cond, L)] = dict(published=old["Cd_counts"], welded=e["Cd_counts"],
                                            shift=dcd, dCl_counts=dcl, role=role,
                                            published_cells=old.get("mesh_cells"),
                                            welded_cells=e["mesh_cells"])
    write("tab_generation_null.tex", "".join(rows),
          ["data/rans_forces.json cases.*.superseded_entry (published) and cases.* (welded)"])
    sound = [abs(v["shift"]) for v in out.values() if v["role"] == "sound"]
    seam = [v["shift"] for v in out.values() if v["role"] == "seam"]
    vals["generation_null"] = dict(per_case=out, sound_max_abs_shift=max(sound),
                                   seam_shift_range=[min(seam), max(seam)])


def hinge(vals):
    rows, out = [], {}
    by = {}
    with open(HINGE) as fh:
        for r in csv.DictReader(fh):
            by[(r["condition"], r["geometry_letter"])] = r
    conds = [("Condition CR, M = 0.10", r"\emph{Condition CR}, $M = 0.10$, $C_L = 0.428277635108$"),
             ("Early cruise, M = 0.78", r"\emph{Early cruise}, $M = 0.78$, $C_L = 0.529297087450$"),
             ("Late cruise, M = 0.78", r"\emph{Late cruise}, $M = 0.78$, $C_L = 0.544114800210$")]
    act = {"B": "rigid", "C": "yes", "F": "yes", "H": r"\textbf{no}$^{a}$", "M": "yes",
           "W": r"\textbf{no}$^{b}$"}
    for key, lab in conds:
        q = float(by[(key, "B")]["q_Pa"])
        rows.append(r"\multicolumn{8}{l}{%s, $q = \num{%.2f}$~Pa} \\" % (lab, q) + "\n")
        b = float(by[(key, "B")]["M_h_total_Nm"])
        for L in GEOMS:
            r = by[(key, L)]
            m = float(r["M_h_total_Nm"])
            visc = 100 * float(r["M_h_viscous_Nm"]) / m
            pct = 100 * (m - b) / abs(b)   # signed with dM_h, the existing table convention
            rows.append("%s & %s & $%.4f$ & $%+.4f$ & $%+.1f$ & $%.6f$ & $%.2f$ & %s \\\\\n"
                        % (L, NAMES[L], m, m - b, pct, float(r["C_Mh_region_total"]), visc, act[L]))
            out["%s/%s" % (key, L)] = dict(M_h=m, dM_h=m - b, pct=pct, visc_pct=visc,
                                          C_Mh=float(r["C_Mh_region_total"]), case=r["case"],
                                          surface=r["surface_vtk"])
        rows.append("\\addlinespace\n" if key != conds[-1][0] else "")
    write("tab_hinge_rows.tex", "".join(rows), ["fig/hinge_moment_values.csv"])
    vals["hinge"] = out


def rbm(vals):
    rows_mx, rows_u, out = [], [], {}
    for cond, c in COND.items():
        base = None
        mx = {}
        for L in GEOMS:
            p, gen = derived_source.resolve(c["prefix"], L)
            if gen != "welded":
                sys.exit("REFUSED: %s%s resolved to %s, not welded" % (c["prefix"], L, gen))
            mx[L] = json.loads(Path(p).read_text())["root_bending"]["RBM_total_Nm"]
        base = mx["B"]
        rows_mx.append(r"%s $M_x$ [N\,m] & " % c["label"] + " & ".join("$%.2f$" % mx[L] for L in GEOMS) + r" \\" + "\n")
        rows_u.append(r"%s utilisation & " % c["label"] + " & ".join("$%.3f$" % (mx[L] / base) for L in GEOMS) + r" \\" + "\n")
        out[cond] = dict(Mx=mx, utilisation={L: mx[L] / base for L in GEOMS},
                         pct={L: 100 * (mx[L] / base - 1) for L in GEOMS})
    body = "".join(rows_mx[:1] + rows_u[:1] + ["\\addlinespace\n"] + rows_mx[1:] + rows_u[1:])
    write("tab_rbm_cruise.tex", body, ["results/derived/<prefix><L>_welded.json root_bending.RBM_total_Nm "
                                       "via fig/derived_source.py"])
    vals["rbm"] = out


def trim_legs(d, vals):
    rows, out = [], {}
    for cond, c in COND.items():
        tgt = d["trims"][cond]["target_CL"]
        rows.append(r"\multicolumn{7}{l}{\emph{%s}, target $C_L = %.12f$} \\" % (c["label"], tgt) + "\n")
        for L in GEOMS:
            e = d["cases"]["%s%s_trim" % (c["prefix"], L)]
            legs = e["trim_history"] + [dict(leg=e["leg"], alpha_deg=e["alpha_deg"], Cl=e["Cl"], Cd=e["Cd"],
                                             latest_time=e["endTime"])]
            for i, lg in enumerate(legs):
                final = i == len(legs) - 1
                nxt = "" if final else "$%+.6f$" % (legs[i + 1]["alpha_deg"] - lg["alpha_deg"])
                rows.append("%s & %d & %d & %.6f & %.7f & $%+.3f$ & %.3f & %s \\\\\n"
                            % (L if i == 0 else "", lg["leg"], int(lg["latest_time"]), lg["alpha_deg"],
                               lg["Cl"], (lg["Cl"] - tgt) * 1e4, lg["Cd"] * 1e4,
                               nxt if not final else "trimmed"))
            out["%s/%s" % (cond, L)] = dict(n_legs=len(legs), first_residual_counts=(legs[0]["Cl"] - tgt) * 1e4,
                                            final_residual_counts=(legs[-1]["Cl"] - tgt) * 1e4,
                                            total_nudge_deg=legs[-1]["alpha_deg"] - legs[0]["alpha_deg"])
        rows.append("\\addlinespace\n" if cond == "early_cruise" else "")
    write("tab_trim_legs.tex", "".join(rows), ["data/rans_forces.json cases.*_trim.trim_history"])
    vals["trim_legs"] = out


def coverage(d, vals):
    """Case inventory by geometry, condition and mesh generation, counted from the data file."""
    concept = {"B": "rigid baseline", "C": "continuous TE camber", "F": "continuous TE camber",
               "M": "continuous TE camber", "W": "distributed twist", "H": "conventional hinged"}
    cnt, tot = {}, {}
    for n, e in d["cases"].items():
        if e.get("status") != "converged":
            continue
        k = (e["condition"], e["family_letter"], e.get("mesh_generation"))
        cnt[k] = cnt.get(k, 0) + 1
        tot[e["condition"]] = tot.get(e["condition"], 0) + 1
    rows = []
    for L in "BCFMWH":
        cr = cnt.get(("condition_CR", L, "published"), 0) + cnt.get(("condition_CR", L, "wake_refined"), 0)
        rows.append("%s & %s & %d & %d & %d & %d & %d \\\\\n" % (
            L, concept[L], cr,
            cnt.get(("early_cruise", L, "published"), 0), cnt.get(("early_cruise", L, "welded"), 0),
            cnt.get(("late_cruise", L, "published"), 0), cnt.get(("late_cruise", L, "welded"), 0)))
    g = lambda c, gen: sum(v for (cc, _, gg), v in cnt.items() if cc == c and gg == gen)
    rows.append("\\midrule\n\\multicolumn{2}{l}{Totals} & %d & %d & %d & %d & %d \\\\\n" % (
        tot["condition_CR"], g("early_cruise", "published"), g("early_cruise", "welded"),
        g("late_cruise", "published"), g("late_cruise", "welded")))
    write("tab_coverage_rows.tex", "".join(rows), ["data/rans_forces.json cases (status, condition, "
                                                   "family_letter, mesh_generation)"])
    vals["coverage"] = dict(total=sum(tot.values()), by_condition=tot,
                            welded=g("early_cruise", "welded") + g("late_cruise", "welded"),
                            cruise_published=g("early_cruise", "published") + g("late_cruise", "published"))


def mesh_table(vals):
    """Per-geometry surface and as-built cell counts for every condition, from the files that
    define them: Condition CR from the r2 run cards, cruise from the welded owner headers."""
    tri = {"B": 192588, "C": 192588, "M": 192588, "F": 195266, "W": 195266, "H": 195266}
    rc = ROOT.parents[2] / "results/run_cards_r2"
    with open(MESH) as fh:
        wm = {r["case"]: int(r["cells"]) for r in csv.DictReader(fh, delimiter="\t")}
    concept = {"B": "rigid baseline", "C": "continuous TE camber", "M": "continuous TE camber",
               "F": "continuous TE camber", "W": "distributed twist", "H": "conventional hinged"}
    rows, cr = [], {}
    for L in "BCMFWH":
        card = json.loads((rc / ("SW%s_r2_trim.json" % L)).read_text())
        cr[L] = int(card["mesh"]["cells"])
        rows.append("%s & %s & \\num{%d} & \\num{%d} & \\num{%d} & \\num{%d} & pass \\\\\n"
                    % (L, concept[L], tri[L], cr[L], wm["CMP%s_trim" % L], wm["LC%s_trim" % L]))
    write("tab_geom_mesh_rows.tex", "".join(rows),
          ["results/run_cards_r2/SW<L>_r2_trim.json mesh.cells", "data/welded_mesh_facts.tsv cells"])
    vals["mesh_cr_r2_cells"] = dict(cells=cr, range=[min(cr.values()), max(cr.values())])


def mesh(vals):
    with open(MESH) as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    cells = {r["case"]: int(r["cells"]) for r in rows}
    vals["mesh"] = dict(
        cells=cells, cells_range=[min(cells.values()), max(cells.values())],
        layers_achieved=sorted({r["layers_achieved"] for r in rows}),
        layer_thickness_pct=sorted({r["layer_thickness_pct"] for r in rows}),
        nonortho_max_range=[min(float(r["nonortho_max_deg"]) for r in rows),
                            max(float(r["nonortho_max_deg"]) for r in rows)],
        checkmesh_failed_range=[min(int(r["checkmesh_failed"]) for r in rows),
                                max(int(r["checkmesh_failed"]) for r in rows)],
        wing_faces_range=[min(int(r["wing_faces_layered"]) for r in rows),
                          max(int(r["wing_faces_layered"]) for r in rows)])


def main():
    d = json.loads(DATA.read_text())
    vals = {"_generator": "scripts/make_cruise_tables.py"}
    perf(d, vals)
    generation_null(d, vals)
    hinge(vals)
    rbm(vals)
    trim_legs(d, vals)
    coverage(d, vals)
    mesh_table(vals)
    mesh(vals)
    p = OUT / "cruise_values.json"
    p.write_text(json.dumps(vals, indent=1, sort_keys=True) + "\n")
    print("  wrote %s" % p.relative_to(HERE.parent))
    return 0


if __name__ == "__main__":
    sys.exit(main())
