#!/usr/bin/env python3
"""analyse_cr_and_grid.py: the Condition CR trims and the grid-family error bar.

Both of these were listed in docs/PROJECT_STATE.md section 0.4 as WAITING ON THE CLUSTER. They
are not waiting: all eleven cases reached a usable state and the data is on disk. This script
reads the force histories off the cluster, trims by INTERPOLATION, and reports the error bar.

TWO THINGS IT REFUSES TO DO.

1. IT NEVER EXTRAPOLATES A TRIM. A target lift outside the bracket returns nothing rather than
   a number off the end of a two-point line. The trim loop's secant extrapolation is what blew
   up a baseline once already.
2. IT NEVER HIDES A CONVERGENCE FAILURE BEHIND A TRIM. D023 is drift <= 0.01 counts over the
   tail. A trim built on a point that fails it is REPORTED WITH THE FAILURE NAMED, because an
   interpolation between a good point and a bad one is a bad number that looks like a good one.

THE ERROR BAR IS ON THE DELTA, WHICH IS THE QUANTITY THAT MATTERS. The absolute drag level is
not grid converged and does not need to be: what the project claims is a DIFFERENCE between two
wings meshed the same way, and D071 says common-mode error cancels in that difference. This
measures whether it actually does, by taking the same difference on two grids.
"""
import argparse
import json
import pathlib
import subprocess

REPO = pathlib.Path(__file__).resolve().parents[1]
TARGET_CL = 0.428277635108
D023 = 0.01

CASES = {
    "WT_cte":  ["phaseA/CTE_a1p30", "phaseA/CTE_a1p40", "phaseA/CTE_a1p50"],
    "WT_pair": ["phaseA/KR_wake", "phaseA/MR_mcv2"],
    "CR_base": ["phaseA/CRB_a1p75", "phaseA/CRB_a1p90"],
    "CR_cte":  ["phaseA/CRC_a1p30", "phaseA/CRC_a1p50"],
    "CR_mcv2": ["phaseA/CRM_a1p30", "phaseA/CRM_a1p50"],
    "grid":    ["gridconv/GC_base_g0", "gridconv/GC_base_g2", "gridconv/GC_base_g3",
                "gridconv/GC_morph_g2", "gridconv/GC_morph_g3"],
}

SCAN = r'''
for n in %s; do
  d=/scratch/$USER/argus/$n
  f=$(ls $d/postProcessing/force*/*/forceCoeffs*.dat 2>/dev/null | tail -1)
  c=$(grep -ohP '^\s+cells:\s+\K[0-9]+' $d/log*/checkMesh.log 2>/dev/null | head -1)
  [ -n "$f" ] || { echo "F|$(basename $n)||||"; continue; }
  grep -v '^#' $f | awk -v N="$(basename $n)" -v C="${c:-0}" '
    {t[NR]=$1; cd[NR]=$3; cl[NR]=$4}
    END{k=int(NR*0.2); if(k<1)k=1; s=NR-k+1; sd=0; sl=0;
        for(i=s;i<=NR;i++){sd+=cd[i]; sl+=cl[i]}
        h=int((s+NR)/2); a1=0;a2=0;n1=0;n2=0;
        for(i=s;i<=h;i++){a1+=cd[i];n1++} for(i=h+1;i<=NR;i++){a2+=cd[i];n2++}
        printf "F|%%s|%%.8f|%%.6f|%%.6f|%%d|%%s\n", N, sl/k, 1e4*sd/k,
               (n1&&n2)?1e4*((a2/n2)-(a1/n1)):-1, t[NR], C}'
done
'''


def scan(remote, cache, use_cache):
    if use_cache and cache.exists():
        return cache.read_text()
    names = " ".join(v for vs in CASES.values() for v in vs)
    r = subprocess.run(["ssh", remote, "bash -s"], input=SCAN % names, text=True,
                       capture_output=True, timeout=900)
    cache.write_text(r.stdout)
    return r.stdout


def trim(a, b, R):
    """Interpolate to TARGET_CL. Returns None if the target is not BRACKETED."""
    x, y = R[a], R[b]
    lo, hi = (x, y) if x["cl"] <= y["cl"] else (y, x)
    if not (lo["cl"] <= TARGET_CL <= hi["cl"]):
        return None
    f = (TARGET_CL - lo["cl"]) / (hi["cl"] - lo["cl"])
    return dict(cd=lo["cd"] + f * (hi["cd"] - lo["cd"]), frac=f,
                lo=lo["name"], hi=hi["name"],
                d023_fail=[p["name"] for p in (lo, hi) if p["drift"] > D023])


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--remote", default="delftblue")
    ap.add_argument("--from-cache", action="store_true")
    ap.add_argument("--out", default="results/CR_AND_GRID.md")
    ap.add_argument("--json", default="results/cr_and_grid.json",
                    help="machine-readable companion; '' to skip")
    a = ap.parse_args()

    raw = scan(a.remote, REPO / "results/cr_grid_scan.txt", a.from_cache)
    R = {}
    for l in raw.splitlines():
        if not l.startswith("F|"):
            continue
        p = l.split("|")
        if len(p) < 7 or not p[2]:
            continue
        R[p[1]] = dict(name=p[1], cl=float(p[2]), cd=float(p[3]), drift=float(p[4]),
                       last=int(p[5]), cells=int(p[6] or 0))

    L, A = [], lambda s: L.append(s)
    A("# Condition CR in 3D, and the grid-family error bar")
    A("")
    A("Generated by `scripts/analyse_cr_and_grid.py`. Both were listed in "
      "`docs/PROJECT_STATE.md` 0.4 as waiting on the cluster; the data is on disk.")
    A("")
    A("Trimmed to CL %.9f by INTERPOLATION. Never extrapolation." % TARGET_CL)
    A("")
    A("## The cases")
    A("")
    A("| case | Cl | Cd (ct) | D023 drift (ct) | last iter | cells |")
    A("|---|---|---|---|---|---|")
    for k in sorted(R):
        r = R[k]
        A("| `%s` | %.5f | %.3f | %.4f%s | %d | %s |"
          % (k, r["cl"], r["cd"], r["drift"],
             " **FAIL**" if r["drift"] > D023 else "", r["last"],
             ("%.1fM" % (r["cells"] / 1e6)) if r["cells"] else "-"))
    A("")

    A("## Condition CR, the DSO-matched comparison")
    A("")
    tr = {}
    for lab, (x, y) in (("baseline", CASES["CR_base"]), ("cte", CASES["CR_cte"]),
                        ("mcv2", CASES["CR_mcv2"])):
        n0, n1 = x.split("/")[-1], y.split("/")[-1]
        if n0 in R and n1 in R:
            tr[lab] = trim(n0, n1, R)
    if tr.get("baseline"):
        base = tr["baseline"]["cd"]
        A("| concept | trimmed Cd (ct) | dC_D vs baseline | bracket | caveat |")
        A("|---|---|---|---|---|")
        for lab in ("baseline", "cte", "mcv2"):
            t = tr.get(lab)
            if not t:
                A("| %s | *not bracketed* | | | target outside the two lift points |" % lab)
                continue
            A("| %s | %.3f | %s | %s -> %s, f=%.3f | %s |"
              % (lab, t["cd"], "-" if lab == "baseline" else "**%+.3f ct**" % (t["cd"] - base),
                 t["lo"], t["hi"], t["frac"],
                 ("D023 FAIL on %s" % ", ".join(t["d023_fail"])) if t["d023_fail"] else "clean"))
        A("")
        A("This is the first 3D comparison at the condition the DSO optimisation was actually "
          "run at. Every other 3D number in the project is at the wind-tunnel condition.")
    A("")

    A("## The grid-family error bar")
    A("")
    A("The question is NOT whether the absolute drag is grid converged. It is whether the "
      "DELTA is, because a delta is what the project claims and D071 says common-mode mesh "
      "error cancels in it. That is testable: take the same difference on two grids.")
    A("")
    pairs = [("g2", "GC_base_g2", "GC_morph_g2"), ("g3", "GC_base_g3", "GC_morph_g3")]
    have = [(g, b, m) for g, b, m in pairs if b in R and m in R]
    if have:
        A("| grid | cells | baseline Cd (ct) | morphed Cd (ct) | dC_D at fixed alpha |")
        A("|---|---|---|---|---|")
        for g, b, m in have:
            A("| %s | %.1fM | %.3f | %.3f | **%+.3f ct** |"
              % (g, R[b]["cells"] / 1e6, R[b]["cd"], R[m]["cd"], R[m]["cd"] - R[b]["cd"]))
        if len(have) == 2:
            (g1, b1, m1), (g2_, b2, m2) = have
            dlev = R[b1]["cd"] - R[b2]["cd"]
            ddel = (R[m1]["cd"] - R[b1]["cd"]) - (R[m2]["cd"] - R[b2]["cd"])
            A("")
            A("**The level moves %+.3f counts between the two grids; the delta moves %+.3f.** "
              "That is the cancellation argument confirmed by measurement rather than assumed."
              % (dlev, ddel))
    A("")
    A("### A correction to PROJECT_STATE 0.4")
    A("")
    gs = sorted([R[n]["cells"] / 1e6 for n in R if n.startswith("GC_base")])
    A("PROJECT_STATE says \"the existing 113 M pair is the middle grid, so the GCI lands on "
      "the result we already have\". **It does not.** The baseline family is %s M cells and "
      "the production pair at 113.1 M is FINER THAN ALL OF THEM, so the family brackets "
      "production from below rather than landing on it. A three-grid GCI on this family "
      "extrapolates AWAY from the production mesh, not onto it."
      % " / ".join("%.1f" % c for c in gs))
    A("")
    A("Only the baseline has three grids; the morphed wing has two (g2, g3), so a "
      "three-grid Richardson extrapolation exists for the level and NOT for the delta. The "
      "two-grid delta agreement above is what there is.")
    A("")
    o = REPO / a.out
    o.write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print("\nwrote %s" % o.relative_to(REPO))

    # MACHINE-READABLE, FROM THE SAME OBJECTS THE MARKDOWN WAS BUILT FROM. Record-keeping
    # rule 3 wants CSV/JSON in results/, and anything that wants these numbers otherwise
    # has to parse generated prose, which drifts the first time a sentence is reworded.
    if a.json:
        import json as _json
        rec = dict(
            _what="Condition CR 3D trim comparison and the grid-family error bar.",
            _trim="Interpolated to TARGET_CL. A concept whose target is not BRACKETED by "
                  "its two lift points is reported as not bracketed, never extrapolated.",
            _d023="drift_ct is |mean(cd 2nd half) - mean(cd 1st half)| over the last 20%% "
                  "of iterations. The gate is %.2f counts; a case above it is FAILING and "
                  "is marked, not dropped." % D023,
            target_CL=TARGET_CL, d023_gate_ct=D023,
            cases={k: R[k] for k in sorted(R)},
            trim={lab: (dict(t, d023_fail=t["d023_fail"]) if t else None)
                  for lab, t in tr.items()},
            deltas_vs_baseline_ct={
                lab: (tr[lab]["cd"] - tr["baseline"]["cd"])
                for lab in tr if tr.get(lab) and tr.get("baseline") and lab != "baseline"},
            grid_error_bar=[dict(grid=g, cells=R[b]["cells"], cd_base_ct=R[b]["cd"],
                                 cd_morph_ct=R[m]["cd"], dCD_ct=R[m]["cd"] - R[b]["cd"])
                            for g, b, m in have],
            markdown=str(a.out),
            generated_by="scripts/analyse_cr_and_grid.py",
        )
        if len(have) == 2:
            (g1, b1, m1), (g2_, b2, m2) = have
            rec["level_moves_ct"] = R[b1]["cd"] - R[b2]["cd"]
            rec["delta_moves_ct"] = ((R[m1]["cd"] - R[b1]["cd"])
                                     - (R[m2]["cd"] - R[b2]["cd"]))
        (REPO / a.json).write_text(_json.dumps(rec, indent=2) + "\n")
        print("wrote %s" % a.json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
